Repository krishnaacharyaa/wanderlust, pull requests merged in 2024-05, with the labels that each got.

#201 enhancement-#102: Refactoring of all the md: to sm:
  frontend/src/components/admin-container.tsx
  frontend/src/components/admin-sidebar.tsx
  frontend/src/components/blog-feed.tsx
  frontend/src/components/hero.tsx
  frontend/src/components/post-card.tsx
  frontend/src/components/skeletons/post-card-skeleton.tsx
  frontend/src/layouts/footer-layout.tsx
  frontend/src/layouts/header-layout.tsx
  frontend/src/pages/add-blog.tsx
  frontend/src/pages/admin-blogs.tsx
  frontend/src/pages/admin-users.tsx
  frontend/src/pages/details-page.tsx
  frontend/src/pages/home-page.tsx
  frontend/src/pages/signin-page.tsx
  frontend/src/pages/signup-page.tsx
Labels: gssoc, level2

#207 BUGFIX-#165: Categories Sidebar UI issue
  frontend/src/components/blog-feed.tsx
Labels: gssoc, level1

#214 fix-#110: Latest post card skeleton alignment bug fixed
  frontend/src/components/skeletons/latest-post-card-skeleton.tsx
Labels: gssoc, level1

#218 BUGFIX-#193: User can access undefined routes.
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/not-found.tsx
Labels: gssoc, level3

#259 fix-#258: Now icons are visible in mobile screen instead of both button + icons ( login, logout and creat post) and aligned header too.
  frontend/src/layouts/header-layout.tsx
Labels: gssoc, level3

#292 fix-#270: Added the border and the background-color to differentiate white background of the blog post card.
  frontend/src/components/featured-post-card.tsx
Labels: gssoc

#318 fix-#263: Update readme doc
  README.md
Labels: gssoc, level3

#371 fix-#108: Fixed bug by adding responsiveness and inlining the skeleton.
  frontend/src/components/skeletons/post-card-skeleton.tsx
Labels: gssoc, level1
